# Generated by Django 5.0.6 on 2024-06-28 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
