# Generated by Django 5.0.6 on 2024-06-28 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(default=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
